### ISSUE TITLE
Support for {empty}

### ISSUE THREAD

**Issue by gwinnem** [hodgef/simple-keyboard#1768]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When {empty} is defined i would like to see a button with no text and the button being disabled

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
You can spawn an empty button by adding `{//}` to your layout. For example:

https://codesandbox.io/s/condescending-phoebe-etprbf?file=/src/index.js

If you'd like to style it differently, you can use CSS to that effect like so:

```css
.hg-button.hg-standardBtn[data-skbtn="{//}"]
{
  background: transparent;
  box-shadow: none;
  border: none;
  pointer-events: none;
} 
```
