### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by BenedictLang** [hodgef/simple-keyboard#2007]
**Describe the solution you'd like**
There is a less code option for the margins of the key when you use `gap` instead of margins and `:last-child`.

[CanIUse](https://caniuse.com/?search=gap) -> 94% coverage

```css
/* remove */
.hg-button:not(:last-child) {
  margin-right: 5px
}

/* add to .hg-row */
.hg-row {
  gap: 5px
}
```
