### ISSUE TITLE
Removing margin from buttons to avoid unresponsive empty space

### ISSUE THREAD

**Issue by tikotus** [hodgef/simple-keyboard#2471]
**Is your feature request related to a problem? Please describe.**
Current default keyboard uses margin to add space between buttons. This margin area however does not respond to clicks, making the empty are non-interactive, unlike the empty area for example in the normal iPhone virtual keyboard. This causes lots of errors while typing.

**Describe the solution you'd like**
One solution could be to wrap button visuals in another button with padding. This seems like a non-trivial task for someone who quickly wants a well behaving virtual keyboard.

**Comment by hodgef** [comment]
Hello @tikotus,

You can edit the keyboard styles with CSS. I think this should work well for your use-case and relatively trivial.

Regards,
Francisco Hodge

**Comment by tikotus** [comment]
I think I was unclear, or I'm missing something.
I like the way the current default keyboard looks. The margin between the buttons is nice. But the margin is not clickable. I can indeed remove the margin using css, but then it won't look as nice. I would like there to be the space between the buttons, but it should be clickable. I'm unable to figure out a way to do this with css.
One way it could be possible is to wrap the visuals of the button inside another button with (clickable) padding, but this requires modifying the rendered hierarchy, quickly going out of scope for "trivial".

Would you agree, or am I missing some simple solution for keeping the nice empty space between the buttons while keeping it clickable?

**Comment by hodgef** [comment]
The default theme uses the `.hg-button` to style each button. Because of this, the gap cannot be inside of the button. This is why the CSS needs to be edited to craft a theme that styles the button on the `.hg-button span` instead.

Here's a quick example:

https://codesandbox.io/p/devbox/sharp-bash-3phnq6?from-embed=&workspaceId=ws_KiAsSPBbX5zgs1YKXQrsfN

```js
const keyboard = new Keyboard({
  theme: "my-theme", // < this will remove default theme class "hg-theme-default"
  onChange: (input) => onChange(input),
  onKeyPress: (button) => onKeyPress(button),
});
```

```css
.simple-keyboard {
  max-width: 850px;
}

.simple-keyboard .hg-row {
  display: flex;
}

.simple-keyboard .hg-button {
  padding: 2px;
  flex: 1;
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
}

.simple-keyboard .hg-button span {
  display: flex;
  min-width: 20px;
  min-height: 30px;
  border: 1px solid black;
  border-radius: 5px;
  align-items: center;
  justify-content: center;
  padding: 0 5px;
  box-sizing: border-box;
}

.simple-keyboard .hg-button.hg-button-space {
  flex: 10;
}
```

https://hodgef.com/simple-keyboard/documentation/options/theme/
